server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/document?createDatabaseIfNotExist=true
    username: root
#    password: votre_mot_de_passe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Configuration pour la taille maximale des fichiers téléversés

  servlet:
    multipart:
      max-file-size:  10240MB
      max-request-size: 10240MB

# Paramètres spécifiques à votre application (par exemple, pour gérer le chemin de stockage)
#app:
#  document:
#    storage-path: /chemin/vers/le/repertoire/de/stockage
#
## Configuration de la sécurité (si nécessaire)
#security:
#  basic:
#    enabled: false
